/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/document_file_folder.glb --transform 
Files: public/models/document_file_folder.glb [51.5MB] > /Users/vshasi/Code/vishal_portfolio/document_file_folder-transformed.glb [4.85MB] (91%)
Author: Kami Rapacz (https://sketchfab.com/kuroderuta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/document-file-folder-11390179bba7462484d344e2fe22c703
Title: Document File Folder
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/document_file_folder-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="A4_Page3Shape_2_0" geometry={nodes.A4_Page3Shape_2_0.geometry} material={materials.A4_Page3Shape} />
        <mesh name="Folder_1Shape" geometry={nodes.Folder_1Shape.geometry} material={materials.Folder_1Shape} morphTargetDictionary={nodes.Folder_1Shape.morphTargetDictionary} morphTargetInfluences={nodes.Folder_1Shape.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('/document_file_folder-transformed.glb')
