/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ford_f150_raptor.glb --transform 
Files: public/models/ford_f150_raptor.glb [43.53MB] > /Users/vshasi/Code/vishal_portfolio/ford_f150_raptor-transformed.glb [4.98MB] (89%)
Author: Outlaw Games™ (https://sketchfab.com/Outlaw_Games)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ford-f150-raptor-5bde9684bf6d40e0902ee8e482ad1063
Title: Ford F150 Raptor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ford_f150_raptor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['glass.006']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['goma.002']} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['crome.011']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['carpet.003']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['keyhole.001']} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['symbols.001']} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['stitch.001']} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.leathers} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['rivet.001']} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['discbrake.004']} />
      <mesh geometry={nodes.Object_81.geometry} material={materials['vehiclelights.010']} />
      <mesh geometry={nodes.Object_101.geometry} material={materials['undercarriage.004']} />
      <mesh geometry={nodes.Object_151.geometry} material={materials['vehicle_generic_carbon.001']} />
      <mesh geometry={nodes.Object_157.geometry} material={materials['symbol3.001']} />
      <mesh geometry={nodes.Object_166.geometry} material={materials['grill.001']} />
      <mesh geometry={nodes.Object_169.geometry} material={materials['pedals.001']} />
      <mesh geometry={nodes.Object_182.geometry} material={materials['665.001']} />
      <mesh geometry={nodes.Object_286.geometry} material={materials['vehicle_generic_detail2.001']} />
      <mesh geometry={nodes.Object_305.geometry} material={materials['MAATE_WhelenDominator.001']} />
      <mesh geometry={nodes.Object_364.geometry} material={materials['11BLACK.001']} />
      <mesh geometry={nodes.Object_393.geometry} material={materials['vehiclelights128.001']} />
      <mesh geometry={nodes.Object_396.geometry} material={materials['lasluces.001']} />
      <mesh geometry={nodes.Object_406.geometry} material={materials['genesis.001']} />
      <mesh geometry={nodes.Object_412.geometry} material={materials['console.003']} />
      <mesh geometry={nodes.Object_452.geometry} material={materials['for_badge.001']} />
      <mesh geometry={nodes.Object_478.geometry} material={materials['deng.001']} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['vehicle_generic_tyrewallblack.001']} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['vehicle_generic_tyrewallblack.002']} />
      <mesh geometry={nodes.Object_409.geometry} material={materials['Coban_tex.003']} />
    </group>
  )
}

useGLTF.preload('/ford_f150_raptor-transformed.glb')
