/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cnc_machine.glb --transform 
Files: public/models/cnc_machine.glb [15.29MB] > /Users/vshasi/Code/vishal_portfolio/cnc_machine-transformed.glb [1.32MB] (91%)
Author: Khushbushah (https://sketchfab.com/Khushbushah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cnc-machine-af387e70d78a4ba4886af58dd7aec96b
Title: CNC Machine
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cnc_machine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_302.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object_322.geometry} material={materials.M_14___Default} />
    </group>
  )
}

useGLTF.preload('/cnc_machine-transformed.glb')
