/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/schaefer_gas_aluminum_furnace.glb --transform 
Files: public/models/schaefer_gas_aluminum_furnace.glb [39.55MB] > /Users/vshasi/Code/vishal_portfolio/schaefer_gas_aluminum_furnace-transformed.glb [2.16MB] (95%)
Author: The Schaefer Group (https://sketchfab.com/schaefergroup)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/schaefer-gas-aluminum-furnace-1ff6be358af648e9aa94de221bad73aa
Title: Schaefer Gas Aluminum Furnace
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/schaefer_gas_aluminum_furnace-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Mc_channel_MC4X138(1)1_Silver_Painted_Metal_0'].geometry} material={materials.PaletteMaterial001} rotation={[0, Math.PI / 2, 0]} scale={0.026} />
      <mesh geometry={nodes['Cut-Extrude4_Refractory_0'].geometry} material={materials.PaletteMaterial002} rotation={[0, Math.PI / 2, 0]} scale={0.026} />
      <mesh geometry={nodes.NONE_Mesh_guard_0.geometry} material={materials.Mesh_guard} position={[-0.667, 3.48, 4.629]} rotation={[0, -Math.PI / 2, 0]} scale={0.026} />
      <mesh geometry={nodes.Plane001_Catwalk_0.geometry} material={materials.Catwalk} position={[0.792, 3.329, 1.879]} rotation={[-Math.PI / 2, 0, 0]} scale={0.026} />
    </group>
  )
}

useGLTF.preload('/schaefer_gas_aluminum_furnace-transformed.glb')
