/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/resin_3d_printer.glb --transform 
Files: public/models/resin_3d_printer.glb [51.06MB] > /Users/vshasi/Code/vishal_portfolio/resin_3d_printer-transformed.glb [2.52MB] (95%)
Author: YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/resin-3d-printer-b77b9c1c4c1b4a35a867beebeac5de60
Title: Resin 3D Printer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/resin_3d_printer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mgn12h_Material001_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.228, 0.007]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1.25} />
      <mesh geometry={nodes.baza_lcd_0.geometry} material={materials.material} position={[0, -0.008, 0.095]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.capac_Material029_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.187, 0.095]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BUTTON_Material004_0.geometry} material={materials.PaletteMaterial003} position={[0.048, -0.052, 0.191]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/resin_3d_printer-transformed.glb')
